### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#43]
With camp v16.0.1 on node v5.6.0, this crashed my server:

    node_modules/camp/lib/camp.js:152
            var strquery = chunks.toString();
                             ^
    
    TypeError: Cannot read property 'toString' of undefined
        at IncomingMessage.<anonymous> (node_modules/camp/lib/camp.js:152:30)
        at emitNone (events.js:80:13)
        at IncomingMessage.emit (events.js:179:7)
        at endReadableNT (_stream_readable.js:906:12)
        at nextTickCallbackWith2Args (node.js:475:9)
        at process._tickCallback (node.js:389:17)

Maybe using `String(chunks || '')` could solve this? Or add a check like the `chunks === undefined` above.

**Comment by jankeromnes** [comment]
:+1: thanks!
