### ISSUE TITLE
Server crashes with "Can't set headers after they are sent."

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#58]
```bash
_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at getCompressedStream (/home/janx/janitor/node_modules/camp/lib/camp.js:235:9)
    at ServerResponse.res.compressed (/home/janx/janitor/node_modules/camp/lib/camp.js:116:12)
    at ajaxEnd (/home/janx/janitor/node_modules/camp/lib/camp.js:493:15)
```

**Comment by jankeromnes** [comment]
Note: This happens when the server calls the same `end()` callback twice. Camp used to ignore the second attempt, but now the server crashes. Not sure what the best behavior is (my use-case was: call back when a long operation is finished, or call back after 1 minute to prevent browser retries).

**Comment by jankeromnes** [comment]
Thanks! 👍
