### ISSUE TITLE
TypeError: Cannot read property 'slice' of null (with node 9.1.0)

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#65]
```
[2017-11-13T14:29:21.426Z] [fail] unhandled promise rejection TypeError: Cannot read property 'slice' of null
    at getQueries (/home/jan/janitor/node_modules/camp/lib/camp.js:239:34)
    at Array.pathLayer (/home/jan/janitor/node_modules/camp/lib/camp.js:821:9)
    at bubble (/home/jan/janitor/node_modules/camp/lib/camp.js:406:26)
    at next (/home/jan/janitor/node_modules/camp/lib/camp.js:407:46)
    at Array.eventSourceLayer (/home/jan/janitor/node_modules/camp/lib/camp.js:616:49)
    at bubble (/home/jan/janitor/node_modules/camp/lib/camp.js:406:26)
    at next (/home/jan/janitor/node_modules/camp/lib/camp.js:407:46)
    at Array.ajaxLayer (/home/jan/janitor/node_modules/camp/lib/camp.js:516:39)
    at bubble (/home/jan/janitor/node_modules/camp/lib/camp.js:406:26)
    at next (/home/jan/janitor/node_modules/camp/lib/camp.js:407:46)
```

**Comment by jankeromnes** [comment]
Note: The problem appeared when using `node 9.1.0`. It disappeared again when reverting to `node 8.9.1`.

**Comment by paulmelnikow** [comment]
This was reported at badges/shields#1290 and is reproducible in Shields unit tests. A fix would be helpful for developers running Node 9.

```
  1) The server
       should produce colorscheme badges:
     Uncaught TypeError: Cannot read property 'slice' of null
      at getQueries (node_modules/camp/lib/camp.js:239:34)
      at catchpath (node_modules/camp/lib/camp.js:902:3)
      at Array.routeLayer (node_modules/camp/lib/camp.js:864:7)
      at bubble (node_modules/camp/lib/camp.js:406:26)
      at next (node_modules/camp/lib/camp.js:407:46)
      at Array.pathLayer (node_modules/camp/lib/camp.js:837:16)
      at bubble (node_modules/camp/lib/camp.js:406:26)
      at next (node_modules/camp/lib/camp.js:407:46)
      at Array.eventSourceLayer (node_modules/camp/lib/camp.js:616:49)
      at bubble (node_modules/camp/lib/camp.js:406:26)
      at next (node_modules/camp/lib/camp.js:407:46)
      at Array.ajaxLayer (node_modules/camp/lib/camp.js:516:39)
      at bubble (node_modules/camp/lib/camp.js:406:26)
      at next (node_modules/camp/lib/camp.js:407:46)
      at Array.wsLayer (node_modules/camp/lib/camp.js:505:50)
      at bubble (node_modules/camp/lib/camp.js:406:26)
      at next (node_modules/camp/lib/camp.js:407:46)
      at Array.genericLayer (node_modules/camp/lib/camp.js:443:5)
      at bubble (node_modules/camp/lib/camp.js:406:26)
      at listener (node_modules/camp/lib/camp.js:400:3)
      at Camp.<anonymous> (node_modules/camp/lib/camp.js:363:45)
      at parserOnIncoming (_http_server.js:619:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
```

**Comment by espadrine** [comment]
Huh, GitHub stopped sending me notifications for new issues for some reason.

I noticed this issue and fixed it here: https://github.com/espadrine/sc/commit/a7f47ea62dd07beb36402fd3d4ff3d21aa2277c4

**Comment by jankeromnes** [comment]
Thanks for fixing this! 👍 💯

**Comment by styfle** [comment]
For posterity, the breaking change was introduced in Node 9.0.0 with https://github.com/nodejs/node/pull/13606
